add appendTpl
SBoudrias/mem-fs-editor pull request #160
Opened 2021-03-11 11:18 UTC by shladdergoo

Add: appendTpl(filepath, contents, context[, templateOptions[, [options]])

This acts as an overload to append() allowing the new content to be parsed as an ejs template prior to appending.
The behaviour of append() is not changed.

2021-03-20 13:47 UTC, mshima requested changes
I've waited some time to see if I change my mind, but I didn't.

We should add a parameter option to `append` instead, kind of how `copy` works
https://github.com/SBoudrias/mem-fs-editor/blob/3ff18e26c52dc30d8f371bcc72c1884f2ea706d6/lib/actions/copy.js#L64-L66
Could be simpler like `{template: true}` or `{processTemplate: true}`

IMO `appendTpl` makes for sense passing `templatePath` instead of `contents`.

2021-03-23 16:50 UTC, shladdergoo commented
Can I just check my understanding of your suggestion?

For appendTpl, should templatePath be the path to a templated file whose tokens will be replaced by values in the context?

2021-03-27 18:49 UTC, mshima approved these changes

2021-03-27 18:51 UTC, mshima commented
Nevermind, my proposal is best fit at copyTpl.

2021-03-27 18:51 UTC, merged

2021-03-27 18:55 UTC, mshima commented
Thanks @shladdergoo